const keyMirror = require('keymirror');

module.exports = keyMirror({
  API_CALL: null,

  AUTHENTICATION_LOGIN_FAILURE: null,
  AUTHENTICATION_LOGIN_REQUEST: null,
  AUTHENTICATION_LOGIN_SUCCESS: null,
  FORM_PUSH_VALUES: null,
  FORM_REMOVE_VALUES: null,
  FORM_UPDATE_FIELD_VALUE: null,
  FORM_UPDATE_VALUES: null,
  HEALTH_CHECK_FAILURE: null,
  HEALTH_CHECK_REQUEST: null,
  HEALTH_CHECK_SUCCESS: null,
});
